### ISSUE TITLE
Compilation error on names with special characters

### ISSUE THREAD

**Issue by legovader09** [Zezombye/overpy#382]
When working with heroes in the workshop code, and they happen to have a special character in their name, like Lúcio or Torbjörn, the code fails to compile. This is when importing the Gun Game workshop code.
![image](https://github.com/user-attachments/assets/6112f247-fc88-40d1-8dc8-b733193fd150)

Not sure if the hero names are meant to be stringified or not.

**Comment by CactusPuppy** [comment]
Please provide the original code you are trying to decompile.

**Comment by legovader09** [comment]
> Please provide the original code you are trying to decompile.
[gun game.txt](https://github.com/user-attachments/files/17593323/gun.game.txt)
I've attached it as a text file as it's a large file

**Comment by CactusPuppy** [comment]
I am unable to replicate this issue by decompiling and then recompiling the provided code. Make sure you're following the directions provided in the [General usage](https://github.com/Zezombye/overpy/wiki/General-usage) wiki page, as it seems like you are trying to get OverPy to compile the native Workshop output instead of OverPy code.
